#!/usr/bin/env python3
"""Decode real 0x370 EPAS frames from Jordan's capture into a C++ test header.

This is a data-prep codegen step (not visualization). It reads the capture txt,
extracts each frame's 8 data bytes in order, and emits a C++ header consumed by
test/test_native_nag/test_nag_handler.cpp.

Usage:
    python3 scripts/decode_epas_capture.py <capture.txt> -o test/test_native_nag/real_epas_frames.h
"""
import argparse
import re
import sys

# Matches "(HEX: 52 08 08 0F 20 2C 25 55 )" — 8 space-separated hex bytes.
_FRAME_RE = re.compile(
    r"HEX:\s*"
    r"([0-9A-Fa-f]{2})\s+([0-9A-Fa-f]{2})\s+([0-9A-Fa-f]{2})\s+([0-9A-Fa-f]{2})\s+"
    r"([0-9A-Fa-f]{2})\s+([0-9A-Fa-f]{2})\s+([0-9A-Fa-f]{2})\s+([0-9A-Fa-f]{2})"
)

# Lines that mark a new "hold the wheel" warning event (increments the tag).
_WARNING_MARKERS = ("握盘警告", "握方向盘")  # 握盘警告 / 握方向盘


def _expect_echo(b):
    """NagHandler echoes only when handsOn (byte4 bits 7:6) == 0."""
    return ((b[4] >> 6) & 0x03) == 0


def parse_frames(text):
    """Return a list of (bytes_list[8], expectEcho_bool, tag_str), in capture order."""
    out = []
    event = 0
    saw_warning = False
    for line in text.splitlines():
        if any(marker in line for marker in _WARNING_MARKERS) and "警告" in line:
            event += 1
            saw_warning = True
        m = _FRAME_RE.search(line)
        if m:
            b = [int(x, 16) for x in m.groups()]
            tag = ("e%d" % event) if saw_warning else "pre"
            out.append((b, _expect_echo(b), tag))
    return out


_HEADER_PRELUDE = """\
#pragma once
// AUTO-GENERATED by scripts/decode_epas_capture.py --- DO NOT HAND-EDIT.
// Source: Jordan's real 0x370 EPAS capture (steering-wheel nag event).
// Regenerate:
//   python3 scripts/decode_epas_capture.py <capture.txt> -o test/test_native_nag/real_epas_frames.h
#include <cstdint>

struct RealEpasSample {
    uint8_t bytes[8];
    bool expectEcho;
    const char* tag;
};

static const RealEpasSample kRealEpasSamples[] = {
"""

_HEADER_POSTLUDE = """\
};

static const size_t kRealEpasSampleCount = sizeof(kRealEpasSamples) / sizeof(kRealEpasSamples[0]);
"""


def format_header(samples):
    """Render samples (list of (bytes, expectEcho, tag)) as the C++ header text."""
    lines = [_HEADER_PRELUDE]
    for b, eo, tag in samples:
        bs = ", ".join("0x%02X" % x for x in b)
        lines.append("    {{%s}, %s, \"%s\"}," % (bs, "true" if eo else "false", tag))
    lines.append(_HEADER_POSTLUDE)
    return "".join(lines)


def main():
    ap = argparse.ArgumentParser(description="Decode 0x370 capture -> C++ header.")
    ap.add_argument("capture", help="path to the capture .txt")
    ap.add_argument("-o", "--output", default=None, help="output header path (default: stdout)")
    args = ap.parse_args()

    with open(args.capture, encoding="utf-8") as fh:
        text = fh.read()
    samples = parse_frames(text)
    header = format_header(samples)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(header)
        sys.stderr.write("wrote %d frames to %s\n" % (len(samples), args.output))
    else:
        sys.stdout.write(header)


if __name__ == "__main__":
    main()
